language: perl
perl:
   - "5.8"
   - "5.10"
   #- "5.12"
   #- "5.14"
   #- "5.16"
   #- "5.18"

matrix:
   allow_failures:
      - perl: "5.8"

env:
   global:
      # this should speed things up by bypassing external queries
      #- PERL_CPANM_OPT="--mirror-only -q $PERL_CPANM_OPT"
      #- PERL_CPANM_OPT="-q $PERL_CPANM_OPT"
      # don't try to gpg sign with keys we don't have
      - DZSIGN=archive
      # try to run tests parallel
      #- HARNESS_OPTIONS="j8:c"

branches:
    except:
        # these need a different configuration
        - /release\/.*$/
        - /^build\/.*$/

before_install:
   # git bits sometimes needed...
   - git config --global user.name 'Travis-CI'
   - git config --global user.email 'travis@nowhere.dne'

   # this should speed things up, and bypass external queries
   #- export PERL_CPANM_OPT="--mirror-only -q $PERL_CPANM_OPT"
   - echo $PERL_CPANM_OPT
   #- export PERL_CPANM_OPT="-q $PERL_CPANM_OPT"

   # this prevents failing pod tests blowing everything up...
   - cpanm -q TAP::Harness::Restricted || { cat ~/.cpanm/build.log ; false ; }
   - export HARNESS_SUBCLASS=TAP::Harness::Restricted

   # Moose installs in parallel quite nicely.
   - HARNESS_OPTIONS=j8:c cpanm -q Moose       || { cat ~/.cpanm/build.log ; false ; }
   - HARNESS_OPTIONS=j8:c cpanm -q Dist::Zilla || { cat ~/.cpanm/build.log ; false ; }

   # for DZP LinkCheck
   - cpanm --skip-satisfied -q CPANPLUS || { cat ~/.cpanm/build.log ; false ; }
   - cpanp x

install:
   - echo $PERL_CPANM_OPT
   # not so much install our package as all its prereqs
   - dzil authordeps --missing        | cpanm -q || { cat ~/.cpanm/build.log ; false ; }
   - dzil listdeps --author --missing | cpanm -q || { cat ~/.cpanm/build.log ; false ; }

script:
   - unset HARNESS_SUBCLASS HARNESS_OPTIONS
   #- export DZSIGN=archive
   #- unset HARNESS_SUBCLASS
   - dzil test --release --author
