language: perl
perl:
   -  "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"

matrix:
   allow_failures:
      - perl: "5.8"

before_install:
    # gotta love failing pod tests blowing everything up...
    - cpanm -q TAP::Harness::Restricted || { cat ~/.cpanm/build.log ; false ; }
    - export HARNESS_SUBCLASS=TAP::Harness::Restricted

   # avoid dzil iff our perl < v5.10
   - perl -e '$^V lt v5.10' && { cpanm --installdeps . ; exit 0 ; }

   # Deal with all of the DZIL dependancies, quickly and quietly
   # Moose installs in parallel quite nicely.
   - cpanm --force --verbose --skip-satisfied Directory::Scratch
   - HARNESS_OPTIONS=j8:c cpanm -q Moose       || { cat ~/.cpanm/build.log ; false ; }
   - HARNESS_OPTIONS=j8:c cpanm -q Dist::Zilla || { cat ~/.cpanm/build.log ; false ; }

   - dzil authordeps --missing | xargs cpanm -q || { cat ~/.cpanm/build.log ; false ; }
   # for DZP LinkCheck
   - cpanp x

install:
   # a NO-OP, essentially
   - true

script:
   - export DZSIGN=archive
   - if `perl -e '$^V lt v5.10'` ; then prove -lr t/ ; else dzil test --all ; fi
