language: perl
perl:
   - "5.14"

branches:
    except:
        - "release/cpan"

before_install:
   # git bits sometimes needed...
   - git config user.name 'Travis-CI'
   - git config user.email 'travis@nowhere.dne'

   # Moose installs in parallel quite nicely.
   - HARNESS_OPTIONS=j8:c cpanm -q Moose       || { cat ~/.cpanm/build.log ; false ; }
   - HARNESS_OPTIONS=j8:c cpanm -q Dist::Zilla || { cat ~/.cpanm/build.log ; false ; }

   # for DZP LinkCheck
   - cpanm --skip-satisfied -q CPANPLUS || { cat ~/.cpanm/build.log ; false ; }
   - cpanp x

install:
   # bootstrapping!
   - cpanm -q --mirror-only --installdeps Dist::Zilla::PluginBundle::Git::CheckFor || { cat ~/.cpanm/build.log ; false ; }
   - cpanm --notest --verbose --no-interactive Dist::Zilla::PluginBundle::Git::CheckFor
   # not so much install our package as all its prereqs
   - dzil authordeps --missing        | cpanm -q --mirror-only || { cat ~/.cpanm/build.log ; false ; }
   - dzil listdeps --author --missing | cpanm -q --mirror-only || { cat ~/.cpanm/build.log ; false ; }

script:
   - export DZSIGN=archive
   - dzil test --release --author
