sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - dev     # latest point release
  - blead   # latest git commit
env:
  global:
    - COVERAGE=1
before_install:
  - cpanp x
  - eval $(curl https://travis-perl.github.io/init) --auto
